// Code Loader v2026-05-04-0001
// Interruption Framework v2026-04-22-0001
// Copyright (c) 2025-2026 delfineonx
// SPDX-License-Identifier: Apache-2.0

let config = {
  events: [],
  sources: [],
  show_boot_status: true,
  show_error_details: true,
  show_execution_details: false,
  execution_budget_per_tick: 8,
  join_budget_per_tick: 8,
  players_to_mark_as_joined: [],
  handlers_to_preserve: null,
  globals_to_preserve: null,
  shutdown_on_startup_error: true,
};

{
const A=null,B=undefined,C=globalThis,D=Object.create,E=Object.freeze(function(){}),F=Object.freeze(function(){return!0}),G=eval,H=api;
let I=E,J=E,K,L,M,N,O,P,Q,R,S,T,U=[],V=[],W=[],X=[],Y,Z,a,b=D(A),c,d,e,f,g,h,i=[A,A,A,A,A,A],j,k,l=0;
const m={config:config,isPrimaryBoot:!0,stage:0,cursor:0,startTime:0,endTime:0,onStart:F,onLoad:F,onEnd:F,bootJoinStatus:A,bootLeaveRecords:A,reboot:()=>{if(m.stage===0){m.startTime=Date.now();i=[A,A,A,A,A,A];l=0;m.cursor=0;m.stage=1;J=I;I=r}else{n("CL: Reboot ignored; current boot has not finished.",1)}},logBootStatus:(a=!0)=>{let b=i??m._bootErrors,c=0;if(b!=A){c=(b[0]!=A)+(b[2]!=A)+(b[4]!=A)+(b.length-6)}n("CL: Boot completed in "+(m.endTime-m.startTime)+" ms"+(a?c>0?" with "+c+" error"+(c===1?"":"s")+".":" without errors.":"."),1<<(c===0)<<(b==A))},logErrorDetails:(a=!0)=>{let b=i??m._bootErrors;if(b==A){n("CL: Boot error details are no longer available.",4);return}let c=b[0]!=A,d=b[2]!=A,e=b[4]!=A,f=b.length-6,g=c+d+e+f;if(g>0){let h="CL: Boot error details:";if(c){h+="\n   onStart callback\n      "+b[0]+": "+b[1]}if(d){h+="\n   onLoad callback\n      "+b[2]+": "+b[3]}if(e){h+="\n   onEnd callback\n      "+b[4]+": "+b[5]}if(f>0){h+="\n   ["+f+"] code execution error"+(f===1?"":"s");for(let j=6,k=b.length,l=b[j];j<k;l=b[++j]){h+="\n      "+l[0]+" at ("+l[2]+", "+l[3]+", "+l[4]+"): "+l[1]}}n(h,0);return}if(a){n("CL: Boot completed without errors.",2)}},logExecutionDetails:()=>{let a=j??m._bootSources;if(a==A){n("CL: Execution details are no longer available.",4);return}let b="";if(a.length>0){let c=0;for(let d=0,e=a.length,f=a[d];d<e;f=a[++d]){if(f?.[3]){b+='\n"'+f[3]+'" at ('+f[0]+", "+f[1]+", "+f[2]+")";c++}}b="Executed code from ["+c+"] source block"+(c===1?"":"s")+(c===0?".":":")+b}else{b="No code executed; no positions were configured."}n("CL: "+b,3)},logReport:(a=!0,b=!0,c=!1)=>{if(a){m.logBootStatus(b)}if(b){m.logErrorDetails(!a)}if(c){m.logExecutionDetails()}}};
const n=m._log=function(a,b){let c=n.payloads[b],d=a.length;if(d<=950){c[0].str=a;H.broadcastMessage(c)}else{let e=0,f,g;while(e<d){f=e+950;if(f>=d){g=d}else{g=a.lastIndexOf("\n",f-1);if(g<=e){g=f}}c[0].str=a.slice(e,g);H.broadcastMessage(c);e=g<f?g+1:g}}c[0].str=""};
let o=()=>{let a=config.events,b=D(A),c;for(let d=0,e=a.length,f=a[d];d<e;f=a[++d]){let g,h=!1,i;if(typeof f==="string"){g=f}else if(Array.isArray(f)&&typeof f[0]==="string"){g=f[0];h=!!f[1];i=f[2]}else{throw new TypeError("Invalid event entry at index "+d)}if(b[g]){throw new TypeError('Duplicate event name "'+g+'"')}b[g]=1;if(g==="tick"){continue}c=U.length;U[c]=g;V[c]=i;if(g==="onPlayerJoin"){L=E;K=E;W[c]=_=>{if(m.stage<3||m.stage>14){K=typeof _==="function"?_:E}else{L=typeof _==="function"?_:E}};X[c]=()=>m.stage<3||m.stage>14?K:L;if(h){const j=v;C.onPlayerJoin=function(k,l){j.en=1;j.fn=K;j.args=[k,l];j.sid=0;try{return K(k,l)}finally{j.en=0}}}else{C.onPlayerJoin=function(k,l){return K(k,l)}}}else if(g==="onPlayerLeave"){S=E;R=E;W[c]=_=>{if(m.stage<4||m.stage>15){R=typeof _==="function"?_:E}else{S=typeof _==="function"?_:E}};X[c]=()=>m.stage<4||m.stage>15?R:S;if(h){const j=v;C.onPlayerLeave=function(k,l){j.en=1;j.fn=R;j.args=[k,l];j.sid=0;try{return R(k,l)}finally{j.en=0}}}else{C.onPlayerLeave=function(k,l){return R(k,l)}}}else{let w=E;W[c]=_=>{w=typeof _==="function"?_:E};X[c]=()=>w;if(h){const j=v;C[g]=function(k,l,n,p,q,r,s,t,u){j.en=1;j.fn=w;j.args=[k,l,n,p,q,r,s,t,u];j.sid=0;try{return w(k,l,n,p,q,r,s,t,u)}finally{j.en=0}}}else{C[g]=function(k,l,n,p,q,r,s,t,u){return w(k,l,n,p,q,r,s,t,u)}}}}c=U.length;U[c]="tick";V[c]=B;W[c]=_=>{if(m.stage===0){I=typeof _==="function"?_:E}else{J=typeof _==="function"?_:E}};X[c]=()=>m.stage===0?I:J;C.tick=function(x){I(x)}};
let p=()=>{if(m.stage===-3){let c=U.length;while(l<c){let d=U[l],e=V[l];if(e!==B){H.setCallbackValueFallback(d,e)}C[d]=1;Object.defineProperty(C,d,{configurable:!0,set:W[l],get:X[l]});l++}V=B;W=B;X=B;l=0;m.stage=-2}if(m.stage===-2){let c=a.length;while(l<c){b[a[l]]=1;l++}a=B;l=0;m.stage=-1}if(m.stage===-1){J=E;p=B;m.stage=1;G()}};
let q=a=>{let b=H.getPlayerIds();for(let c=0,d=b.length,e;c<d;c++){e=b[c];if(H.checkValid(e)){H.kickPlayer(e,a)}}};
const r=x=>{v.tick();J(x);u()};
const s=(a,b)=>{if(N[a]!==1){let c=M.length;M[c]=a;M[c+1]=b;N[a]=1}};
const t=(a,b)=>{T[T.length]=[a,m.stage,N?.[a]|0];S(a,b)};
const u=()=>{if(m.stage<12){if(m.stage===1){if(k==A){k=D(A)}let a=!0;try{a=!!m.onStart(k)}catch(b){i[0]=b.name;i[1]=b.message}if(!a){return}h=m.config;h=typeof h==="object"?h:{};m._bootErrors=i;k=B;m.stage=2+((K==A)<<(R==A))}if(m.stage===2){O=h.join_budget_per_tick|0;O=O>0?O:1;P=h.players_to_mark_as_joined;Q=D(A);M=[];m.bootJoinStatus=N=D(A);P??=H.getPlayerIds();L=K;K=s;m.stage=3+(R==A)}if(m.stage===3){m.bootLeaveRecords=T=[];S=R;R=t;m.stage=4}if(m.stage===4){Y=h.handlers_to_preserve;Z??=D(A);if(Y!=A){let a=Y.length;while(l<a){Z[Y[l]]=1;l++}}l=0;m.stage=5+(Y==A)}if(m.stage===5){let a=U.length,b;while(l<a){b=U[l];if(!(b in Z)){C[b]=E}l++}l=0;m.stage=6}if(m.stage===6){c=h.globals_to_preserve;d??=D(A);if(c!=A){let a=c.length;while(l<a){d[c[l]]=1;l++}e=Reflect.ownKeys(C)}l=0;m.stage=7+(c==A)}if(m.stage===7){let a=e.length,c;while(l<a){c=e[l];if(!(c in b||c in d)){delete C[c]}l++}l=0;m.stage=8}if(m.stage===8){Y=B;Z=B;c=B;d=B;e=B;m.stage=9|(K==A)<<1}if(m.stage===9){let a=P.length;while(l<a){Q[P[l]]=1;l++}l=0;m.stage=10}if(m.stage===10){let a=H.getPlayerIds();for(let b=0,c=a.length,d,e;b<c;b++){d=a[b];if(!(d in N)){e=M.length;M[e]=d;M[e+1]=!1;N[d]=1}if(d in Q){N[d]=2}}P=B;Q=B;m.stage=11}if(m.stage===11){j=h.sources;j=m._bootSources=Array.isArray(j)?j:[];f=h.execution_budget_per_tick|0;f=f>0?f:1;g=6;m.stage=12|j.length===0}}if(m.stage<16){if(m.stage===12){let a=C.Math.floor,b=f,c,d,e,h,k;while(m.cursor<j.length){c=j[m.cursor];if((c?.length|0)<3){m.cursor++;continue}d=c[0]=a(c[0])|0;e=c[1]=a(c[1])|0;h=c[2]=a(c[2])|0;if((c[3]=H.getBlock(d,e,h))==="Unloaded"){return!1}try{k=H.getBlockData(d,e,h)?.persisted?.shared?.text;G(k)}catch(l){i[g]=[l.name,l.message,d,e,h];g++}m.cursor++;b--;if(b<=0){return}}f=B;g=B;m.stage=13;G()}if(m.stage===13){if(k==A){k=D(A)}let a=!0;try{a=!!m.onLoad(k)}catch(b){i[2]=b.name;i[3]=b.message}if(!a){return}k=B;m.stage=14+((K==A)<<(R==A))}if(m.stage===14){let a=O,b,c;while(l<M.length&&a>0){b=M[l];if(N[b]!==2){G();c=M[l+1];N[b]=2;l+=2;v.en=1;v.fn=L;v.args=[b,c];v.sid=0;try{L(b,c)}catch(d){v.en=0;n("CL [onPlayerJoin]: "+d.name+": "+d.message,0)}v.en=0;l-=2;a--}l+=2}if(l<M.length){return}M=B;N=B;O=B;K=L;L=E;l=0;m.stage=15+(R==A);G()}if(m.stage===15){T=B;R=S;S=E;m.stage=16}}if(m.stage===16){if(k==A){k=D(A)}let a=!0;try{a=!!m.onEnd(k)}catch(b){i[4]=b.name;i[5]=b.message}if(!a){return}k=B;m.stage=17}if(m.stage===17){m.endTime=Date.now();m.onStart=F;m.onLoad=F;m.onEnd=F;m.bootJoinStatus=A;m.bootLeaveRecords=A;m.logReport(!!h.show_boot_status,!!h.show_error_details,!!h.show_execution_details);h=B;i=B;j=B;I=J;J=E;m.isPrimaryBoot=!1;m.stage=0}};
let v;
{
const A=Object.freeze(function(){}),B=Object.freeze([]),C=[A,B,0,0],D=[];
let E=C,F=!0,G=0,H=0,I=0;
const J=v={en:0,fn:A,args:B,rcnt:0,sid:0,noArgs:B,inspect:()=>{return[D,I,G,H,F]},reset:()=>{I=0;G=0;H=0;D.length=0;E=C;J.en=0;J.fn=A;J.args=B;J.rcnt=0;J.sid=0;F=!0},tick:()=>{J.fn=A;J.args=B;J.sid=0;if(!I){return}F=!1;let a=null;while(I){E=D[G];J.args=E[1];J.rcnt=++E[2];J.sid=E[3];try{E[0](...J.args)}catch(b){a=b}D[G]=undefined;G++;I--;if(a){n("IF ["+(E[0]?.name||"<anonymous>")+"]: "+a.name+": "+a.message,0);a=null}}G=0;H=0;D.length=0;E=C;J.en=0;J.rcnt=0;F=!0}};
Object.defineProperty(globalThis.InternalError.prototype,"name",{configurable:!0,get:()=>{if(F){if(J.en){J.en=0;D[H]=[J.fn,J.args,0,J.sid];H++;I++;J.fn=A;J.args=B}}else{J.en=0;E[1]=J.args;E[3]=J.sid;E=C;J.rcnt=0;F=!0}return"InternalError"}})
}
try{m.startTime=Date.now();let w=["#FF775E","500","0.95rem","#FFC23D","500","0.95rem","#20DD69","500","0.95rem","#52B2FF","500","0.95rem","#B06CFF","500","0.95rem"],x=n.payloads=[];for(let y=0;y<=4;y++){x[y]=[{str:"",style:{color:w[y*3],fontWeight:w[y*3+1],fontSize:w[y*3+2]}}]}o();Object.seal(v);C.IF=v;C.CL=m;a=Reflect.ownKeys(C);config=B;o=B;q=B;m.stage=-3;J=p;I=r}catch(z){let $="CL [Startup Error]: "+z.name+": "+z.message+".";n($,0);if(!!config?.shutdown_on_startup_error){I=()=>q($)}}
void 0
}

